# -*- coding: utf-8 -*-
"""abc.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1xAc0QQsyIrPS2VwskDw9LYni1lejregg
"""

# FACE DETECTION 
import numpy as np
import matplotlib.pyplot as plt
import cv2

img = plt.imread("/ab.jpg")

img.shape

plt.imshow(img)

model = cv2.CascadeClassifier("/haarcascade_frontalface_default.xml")

faces = model.detectMultiScale(img, 1.5, 5)

faces

faces [0]

x,y,w,h = faces[0]

print(x)
 print(y)
 print(w)
 print(h)

img = cv2.rectangle(img, (x,y), (x+w , y+h) , (255,0,0), 10)

plt.imshow(img)

for ele in faces:
  x,y,w,h = ele
  img = cv2.rectangle( img, (x,y), (x+w, y+h), (255,0,0), 10)

plt.imshow(img)

